version: 0.2
name: JoinMe
author: Neruxov
main: me.neruxov.joinme.Main
api-version: 1.8

permissions:
  joinme.use:
    default: true
    description: Allows you to use base commands of a plugin

commands:
  joinme:
    description: JoinMe command
    usage: /<command>
  jmreload:
    description: Reloads JoinMe configuration
    usage: /<command>
  ij342nj43h23jk4h23jk4h234h23hlasndjkkjsdmjklmnasjfna:
    description: Connect player to a server (test command)
    usage: /<command>